// priority: 0

ClientEvents.lang("en_us", e => {
    e.renameItem('minecraft:bread', 'Bread Loaf')
    e.renameItem('minecraft:quartz', 'White Quartz')
    e.renameItem('minecraft:flint_and_steel', 'Flint and Flint')
    e.renameItem('minecraft:enchanted_golden_apple', 'Notch Apple')
    e.renameItem('brewinandchewin:sweet_berry_jam', 'Liminal Jam')
    e.renameItem('botania:ender_air_bottle', 'Liminal Air Bottle')
    e.renameItem('antiblocksrechiseled:bright_black', 'Black Hole')
    e.renameItem('neapolitan:white_strawberries', 'Pale Strawberries')
    e.renameItem('farmersdelight:flint_knife', 'Wooden Knife')
    e.renameItem('refurbished_furniture:knife', 'Cutting Knife')
    e.renameItem('storagedrawers:diamond_storage_upgrade', 'Storage Upgrade (V)')
    e.renameItem('storagedrawers:emerald_storage_upgrade', 'Storage Upgrade (VI)')
    e.renameItem('tconstruct:cheese_block', 'Hard Cheese Block')
    e.renameItem('tconstruct:cheese_ingot', 'Hard Cheese Ingot')
    e.renameItem('actually_additions:rice', 'Granular Rice')
    e.renameItem('actuallyadditions:basic_coil', 'Basic Digital Coil')
    e.renameItem('actuallyadditions:advanced_coil', 'Advanced Digital Coil')
    e.renameItem('enderchests:ender_chest', 'Interplanar Chest')
    e.renameItem('supplementaries:slice_map', 'Waterproof Map')
    e.renameItem('simpleradio:copper_wire', 'Copper Cable')
    e.renameItem('immersiveengineering:slag', 'Dull Slag')
    e.renameItem('enderio:silicon', 'Thick Clay')
    e.renameItem('immersiveengineering:tesla_coil', 'Tesla Tower')
    e.renameItem('createaddition:tesla_coil', 'Tesla Charger')
    e.renameItem('thermal:rubber', 'Glue')
    e.renameItem('thermal:cured_rubber', 'Cured Glue')
    e.renameItem('thermal:rubber_block', 'Block of Glue')
    e.renameItem('thermal:cured_rubber_block', 'Block of Cured Glue')
    e.renameItem('dustrial_decor:cardboard', 'Thin Cardboard')
    e.renameItem('create:cardboard', 'Sturdy Cardboard')
    e.renameItem('dustrial_decor:cardboard_helmet', 'Thin Cardboard Helmet')
    e.renameItem('dustrial_decor:cardboard_chestplate', 'Thin Cardboard Chestplate')
    e.renameItem('dustrial_decor:cardboard_leggings', 'Thin Cardboard Leggings')
    e.renameItem('dustrial_decor:cardboard_boots', 'Thin Cardboard Boots')
    e.renameItem('immersiveengineering:dust_wood', 'Fine Sawdust')
    e.renameItem('mekanism:sawdust', 'Rough Sawdust')
    e.renameItem('thermal:sawdust', 'Heavy Sawdust')
    e.renameItem('immersiveengineering:sawdust', 'Sawdust Pile')
    e.renameItem('create:bar_of_chocolate', 'Rich Chocolate')
    e.renameItem('create:chocolate_glazed_berries', 'Rich Chocolate Glazed Berries')
    e.renameItem('refurbished_furniture:raw_vegetable_pizza', 'Raw Pizza')
    e.renameItem('tconstruct:earth_slime_tall_grass', 'Earth Slime Grass')
    e.renameItem('tconstruct:sky_slime_tall_grass', 'Sky Slime Grass')
    e.renameItem('tconstruct:blood_slime_tall_grass', 'Blood Slime Grass')
    e.renameItem('tconstruct:ender_slime_tall_grass', 'Ender Slime Grass')//???? WHY ARE THESE CONSIDERED TALL?? TinkersConstruct/issue #5134
})